name: Claude PR Comment Auto Code

permissions:
  contents: write       # 코드 커밋 가능
  pull-requests: write  # PR 수정 가능
  issues: write         # 코멘트 업데이트 가능
  id-token: write       # AWS OIDC 인증

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-pr-comment:
    # PR 댓글이거나 이슈에서 @claude 멘션이 있을 때 실행
    if: ${{ contains(github.event.comment.body, '@claude') }}
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2

    steps:
      # 1️⃣ 코드 체크아웃 (PR인 경우 PR 브랜치, 이슈인 경우 기본 브랜치)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref || 'main' }}
          fetch-depth: 0

      # 2️⃣ GitHub App token 생성
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # 3️⃣ AWS Bedrock 인증
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # 4️⃣ Claude 코드 액션 실행
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          base_branch: main
          use_bedrock: "true"
          # 올바른 Bedrock Claude 모델 ID 지정
          bedrock_model_id: "anthropic.claude-3-5-sonnet-20240620-v1:0"
          # 댓글 내용에서 @claude 부분 제거 후 전달
          claude_args: ${{ github.event.comment.body }}
          # 컨텍스트 정보 추가
          issue_number: ${{ github.event.issue.number }}
          comment_url: ${{ github.event.comment.html_url }}
